// <auto-generated />
using App1_3.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace App1_3.Migrations
{
    [DbContext(typeof(BannedCoutriesContext))]
    [Migration("20220422211313_InitialDbCreateAndSeedData")]
    partial class InitialDbCreateAndSeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.16");

            modelBuilder.Entity("App1_3.Models.BannedContries", b =>
                {
                    b.Property<int>("ContryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("flag")
                        .HasColumnType("longtext");

                    b.HasKey("ContryId");

                    b.ToTable("Coutries");

                    b.HasData(
                        new
                        {
                            ContryId = 174,
                            CountryName = "Egypt",
                            flag = "https://flagcdn.com/w320/eg.png"
                        },
                        new
                        {
                            ContryId = 8,
                            CountryName = "United States",
                            flag = "https://flagcdn.com/w320/us.png"
                        },
                        new
                        {
                            ContryId = 148,
                            CountryName = "Greece",
                            flag = "https://flagcdn.com/w320/gr.png"
                        },
                        new
                        {
                            ContryId = 96,
                            CountryName = "Iraq",
                            flag = "https://flagcdn.com/w320/iq.png"
                        },
                        new
                        {
                            ContryId = 101,
                            CountryName = "Norway",
                            flag = "https://flagcdn.com/w320/no.png"
                        },
                        new
                        {
                            ContryId = 73,
                            CountryName = "Panama",
                            flag = "https://flagcdn.com/w320/pa.png"
                        },
                        new
                        {
                            ContryId = 141,
                            CountryName = "Benin",
                            flag = "https://flagcdn.com/w320/bj.png"
                        },
                        new
                        {
                            ContryId = 160,
                            CountryName = "Pakistan",
                            flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Flag_of_the_Taliban.svg/320px-Flag_of_the_Taliban.svg.png"
                        },
                        new
                        {
                            ContryId = 54,
                            CountryName = "Iceland",
                            flag = "https://flagcdn.com/w320/is.png"
                        },
                        new
                        {
                            ContryId = 16,
                            CountryName = "Uganda",
                            flag = "https://flagcdn.com/w320/ug.png"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
